// Objective-C API for talking to github.com/xtls/xray-core Go package.
//   gobind -lang=objc github.com/xtls/xray-core
//
// File is generated by gobind. Do not edit.

#ifndef __Entry_H__
#define __Entry_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT void EntryRunMain(void);

#endif
