
// Objective-C API for talking to the following Go packages
//
//	github.com/xtls/xray-core
//
// File is generated by gomobile bind. Do not edit.
#ifndef __V2Ray_FRAMEWORK_H__
#define __V2Ray_FRAMEWORK_H__

#include "Entry.objc.h"
#include "Universe.objc.h"

#endif
